let stockProductos = [
    {id: 1, nombre: "Remera Penguin", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera1.jpeg', cantidad: 1},
    {id: 2, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera2.jpeg', cantidad: 1},
    {id: 3, nombre: "Remera Ralph", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera3.jpeg', cantidad: 1},
    {id: 4, nombre: "Remera Tommy ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera4.jpeg', cantidad: 1},
    {id: 5, nombre: "Remera Lacoste", tipo: "remera", desc: "Remera", precio: 2000, talle: "S", img: './img/remera5.jpeg', cantidad: 1},
    {id: 6, nombre: "Remera Ralph", tipo: "remera", desc: "Remera", precio: 2000, talle: "S", img: './img/remera6.jpeg', cantidad: 1},
    {id: 7, nombre: "Remera Ralph", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: "./img/remera7.jpeg", cantidad: 1},
    {id: 8, nombre: "Remera Lacoste", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera8.jpeg', cantidad: 1},
    {id: 9, nombre: "Remera Lacoste", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera9.jpeg', cantidad: 1},
    {id: 10, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera10.jpeg', cantidad: 1},
    {id: 11, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "S", img: './img/remera11.jpeg', cantidad: 1},
    {id: 12, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera12.jpeg', cantidad: 1},
    {id: 13, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "S", img: './img/remera13.jpeg', cantidad: 1},
    {id: 14, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera14.jpeg', cantidad: 1},
    {id: 15, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera15.jpeg', cantidad: 1},
    {id: 16, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera16.jpeg', cantidad: 1},
    {id: 17, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "S", img: './img/remera17.jpeg', cantidad: 1},
    {id: 18, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "L", img: './img/remera18.jpeg', cantidad: 1},
    {id: 19, nombre: "Remera Lacoste ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera19.jpeg', cantidad: 1},
    {id: 20, nombre: "Chomba Ralph ", tipo: "remera", desc: "Chomba", precio: 2800, talle: "M", img: './img/remera20.jpeg', cantidad: 1},
    {id: 21, nombre: "Chomba Ralph ", tipo: "remera", desc: "Chomba", precio: 2800, talle: "L", img: './img/remera21.jpeg', cantidad: 1},
    {id: 22, nombre: "Chomba Lacoste ", tipo: "remera", desc: "Chomba", precio: 2800, talle: "S", img: './img/remera22.jpeg', cantidad: 1},
    {id: 23, nombre: "Chomba Lacoste ", tipo: "remera", desc: "Chomba", precio: 2800, talle: "L", img: './img/remera23.jpeg', cantidad: 1},
    {id: 24, nombre: "Chomba Lacoste ", tipo: "remera", desc: "Chomba", precio: 2800, talle: "S", img: './img/remera24.jpeg', cantidad: 1},
    {id: 25, nombre: "Chomba Lacoste ", tipo: "remera", desc: "Chomba", precio: 2800, talle: "L", img: './img/remera25.jpeg', cantidad: 1},
    {id: 26, nombre: "Remera Tommy ", tipo: "remera", desc: "Remera", precio: 2000, talle: "S", img: './img/remera26.jpeg', cantidad: 1},
    {id: 27, nombre: "Remera Tommy ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera27.jpeg', cantidad: 1},
    {id: 28, nombre: "Remera Tommy ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera28.jpeg', cantidad: 1},
    {id: 29, nombre: "Remera Tommy ", tipo: "remera", desc: "Remera", precio: 2000, talle: "M", img: './img/remera29.jpeg', cantidad: 1},


]


